###################################################
#                                                 #
# Home Assistant Main Configuration File          #
#                                                 #
###################################################

homeassistant:
  name: !secret name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  customize: !include_dir_merge_named customize
  time_zone: Europe/Stockholm
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 192.168.1.0/24
        - 192.168.0.0/16
        - 172.30.32.2
        - 192.168.1.1

#  customize_glob:
#    light.*:
#      custom_ui_state_card: state-card-custom-ui
#    cover.*:
#      custom_ui_state_card: state-card-custom-ui

customizer:
  custom_ui: hosted
  hide_attributes:
    - node_id
    - value_index
  columns: [350, 700, 1050, 1400, 1850, 2100]

http:
# Uncomment this to add a password (recommended!)
#  api_password: !secret http_password
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
#  trusted_networks:
#    - 192.168.1.0/24
#    - 192.168.0.0/16
#    - 172.30.32.2
#    - 192.168.1.1
  ip_ban_enabled: True
  login_attempts_threshold: 2


# Enable the config screen
default_config:

#Added in 0.87
system_health:

#added in 0.88
person:

#added in 0.94
ssdp:

#added in 0.94
zeroconf:

#Enable Cloud service
cloud:

#Enable Map
map:

# Enables the frontend
frontend:
  extra_html_url:
    - https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/state-card-custom-ui.html
  extra_html_url_es5:
    - https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/state-card-custom-ui-es5.html

# Checks for available updates
updater:

discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history: !include history.yaml
logger: !include logger.yaml
#recorder:
recorder: !include recorder.yaml
# View all events in a logbook
logbook: !include loogbook.yaml

# Track the sun
sun:

# Setup TTS
tts:
  - platform: google_translate
#    service_name: google_say
#    cache: true
#    cache_dir: /config/tts
#    time_memory: 300
#    base_url: !secret base_url

#Include Zones
zone: !include zones.yaml

#Include Cameras
camera: !include cameras.yaml

python_script:

#Added in 0.90
stream:

ifttt:
  key: !secret iftttapi

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  


rflink:
  port: /dev/serial/by-id/usb-Arduino__www.arduino.cc__Arduino_Mega_2560_55639313633351104170-if00
# cd /dev/serial/by-id
# ls
# usb-Arduino__www.arduino.cc__Arduino_Mega_2560_85430353631351209040-if00

history_graph:
  gr1:
    name: Time Graph
    entities:
      - sensor.erik_at_work_week
    hours_to_show: 240
    refresh: 3600

alarm_control_panel:
  - platform: manual_mqtt
    state_topic: home/alarm
    command_topic: home/alarm/set
    pending_time: 60
    trigger_time: 1800
    disarm_after_trigger: false
    delay_time: 30
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_away:
      pending_time: 60
      delay_time: 30


# don't think the folowing is used anymore...
#  show_as_state: driving, moving, places
#  driving_speed: 18
#  max_gps_accuracy: 200
#  max_update_wait:
#    minutes: 45

#googlehome:
#  devices:
#    - host: '192.168.1.233'
#      track_alarms: true
#      track_devices: true
#    - host: '192.168.1.183'
#      track_alarms: true
#      track_devices: true
#    - host: '192.168.1.242'
#      track_alarms: true
#      track_devices: true
#    - host: '192.168.1.237'
#      track_alarms: true
#      track_devices: true
#    - host: '192.168.1.225'
#      track_alarms: true
#      track_devices: true
#zwave:
#  device_config: !include zwave_device_config.yaml

#climate:
#  - platform: broadlink
#    name: "Living Room AC"
#    host: 192.168.1.5
#    mac: '34:ea:34:40:78:ff'
#    ircodes_ini: 'broadlink_climate_codes/qlima.ini'
#    min_temp: 17
#    max_temp: 30
#    target_temp: 21
#    temp_sensor: sensor.livingroom_temperature
#    default_operation: off
#    default_fan_mode: auto
#    customize:
#      operations:
#        - 'off'
#        - on
#        - cool
#        - heat
#        - auto
#        - dry
#        - fan
#      fan_modes:
#        - low
#        - mid
#        - high
#        - auto

influxdb:
  host: 192.168.1.15
  port: 8086
  database: home_assistant
  username: !secret influx_username
  password: !secret influx_password
  default_measurement: "units"
  tags:
    instance: prod
    source: hass

octoprint:
  host: 192.168.1.19
  api_key: !secret octoprint_api
  bed: true
  number_of_tools: 1

#### Merged folders (named) ####
group: !include_dir_merge_named groups
script: !include_dir_merge_named scripts
input_select: !include_dir_merge_named input_select

  #### Merged folders (Lists) ####
notify: !include_dir_merge_list notifications
automation: !include_dir_merge_list automation
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switch
light: !include_dir_merge_list light
binary_sensor: !include_dir_merge_list binary_sensor
#automation old: !include_dir_merge_list automation
cover: !include_dir_merge_list covers
lock: !include_dir_merge_list locks


#media_player: moved to packages
## Sony Amplifier
## Disabled due to broadlink problems
#  - platform: broadlink
#    name: Livingroom Amplifier
#    host: 192.168.1.5
#    mac: '34:ea:34:40:78:ff'
#    ircodes_ini: 'broadlink_media_codes/sony_str_dn1040.ini'
#    ping_host: 192.168.1.62
#    retain: true

## Andersson TV
## Disabled due to broadlink problems
#  - platform: broadlink
#    name: Livingroom Andersson
#    host: 192.168.1.5
#    mac: '34:ea:34:40:78:ff'
#    ircodes_ini: 'broadlink_media_codes/andersson.ini'
#    retain: true


cast:

#sabnzbd: !include sabnzb.yaml

shopping_list:

ffmpeg:

remember_the_milk:
  - name: naesstrom
    api_key: !secret rtm_api_key
    shared_secret: !secret rtm_secret

panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html
  lightning:
    title: 'Realtime Lightning'
    url: 'http://map.blitzortung.org/#5.72/56.399/16.371'
    icon: mdi:weather-lightning

#shell_command:
#  getbilladata: 'PATH=$PATH:/bin && rm -fr /home/hass/.homeassistant/billa.txt && curl -X GET https://opendata-download-metfcst.smhi.se/api/category/pmp3g/version/2/geotype/point/lon/14.938817/lat/56.826237/data.json >> /home/hass/.homeassistant/billa.txt'