resources:
  - url: /local/tracker-card.js?v=0
    type: js

title: Katrinelund
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
views:
    # View tab title.
#  - title: Example
    # Optional unique id for direct access /lovelace/${id}
#    id: example
    # Each view can have a different theme applied.
#    theme: dark-mode
    # The cards to show on this view.
#    cards:
        # The filter card will filter entities for their state
#      - type: entity-filter
#        entities:
#          - device_tracker.erik
#          - device_tracker.sussa
#        state_filter:
#          - 'Home'
#        card_config:
#          type: glance
#          title: People that are home

        # The picture entity card will represent an entity with a picture
#      - type: picture-entity
#        image: https://www.home-assistant.io/images/default-social.png
#        entity: light.bed_light

    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:home-assistant
    # Title of the view. Will be used as the tooltip for tab icon
    title: Second view
    cards:
      - type: weather-forecast
        entity: weather.smhi_home
        # Entities card will take list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Example
        # The entities here will be shown in the same order as specified.
        # Each entriy is an entity ID or a map with extra options.
        entities:
          - light.bathroom
          - switch.brevladan
          - entity: light.livingroom_ambient_lights
            # Override the name to use
            name: LR Lights
      - type: map
        aspect_ratio: 50%
        entities:
        - entity: device_tracker.google_maps_110812454925350234140
          name: Erik
        - entity: device_tracker.google_maps_114557479077035215629
          name: sussa

      - type: light
        entity: light.kitchen_lights
      - type: light
        entity: light.livingroom_ambient_lights

        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.
      - type: custom:tracker-card
        title:
        trackers:
        - sensor.custom_card_tracker
        - sensor.custom_component_tracker
  - icon: mdi:car-multiple
    # Title of the view. Will be used as the tooltip for tab icon
    title: Car view
    cards:
      - type: entities
        # Title of the entities card
        title: Sussas Motorvärmare
        # The entities here will be shown in the same order as specified.
        # Each entriy is an entity ID or a map with extra options.
        entities:
          - sensor.heater_departuretime_sussa
          - sensor.heater_activationtime_sussa
          - sensor.heater_temptime_sussa
          - sensor.heater_forecast_sussa
#The following 3 are from the sonoff POW
          - sensor.carheater_1_current
          - sensor.carheater_1_power
          - sensor.carheater_1_voltage
#these are for the automations
          - input_number.heater_hour_sussa
          - input_number.heater_minute_sussa
          - input_number.heater_delay_sussa
          - input_number.heater_maxmin_sussa
          - input_boolean.workdays_only_sussa
          - entity: switch.engine_heater_sussa
            name: Sussas Carheater
            icon: mdi:radiator
      - type: entities
        # Title of the entities card
        title: Eriks Motorvärmare
        # The entities here will be shown in the same order as specified.
        # Each entriy is an entity ID or a map with extra options.
        entities:
          - sensor.heater_departuretime_erik
          - sensor.heater_activationtime_erik
          - sensor.heater_temptime_erik
          - sensor.heater_forecast_erik
#The following 3 are from the sonoff POW
          - sensor.carheater_2_current
          - sensor.carheater_2_power
          - sensor.carheater_2_voltage
#these are for the automations
          - input_number.heater_hour_erik
          - input_number.heater_minute_erik
          - input_number.heater_delay_erik
          - input_number.heater_maxmin_erik
          - input_boolean.workdays_only_erik
          - entity: switch.engine_heater_erik
            name: Eriks Carheater
            icon: mdi:radiator

  - icon: mdi:security-home
    title: Security
    id: security
    type: vertical-stack
    cards:
      - type: glance
        # Title of the entities card
        title: Front Door
        entities:
          - sensor.front_door
          - switch.front_door_lock
          - sensor.front_door_lock
          - lock.frontdoor2
          - sensor.front_door_opens_today
          - sensor.front_door_open_time_today
      - type: glance
        # Title of the entities card
        title: Side Door
        entities:
          - sensor.side_door
          - switch.side_door_lock
          - sensor.side_door_lock
          - sensor.side_door_opens_today
          - sensor.side_door_open_time_today
      - type: glance
        # Title of the entities card
        title: Patio Door
        entities:
          - sensor.patio_door
          - sensor.patio_door_opens_today
          - sensor.patio_door_open_time_today
      - type: glance
        # Title of the entities card
        title: Bathroom Door
        entities:
          - sensor.bathroomdoor
      - type: alarm-panel
        entity: alarm_control_panel.ha_alarm


  - icon: mdi:cctv
    title: Cameras
    id: cameras
    cards:
      #Livingroom Camera
    - type: picture-glance
      camera_image: camera.livingroom
      title: Livingroom
      entities:
        - light.livingroom_ambient_lights
      # Bedroom Camera
    - type: picture-glance
      camera_image: camera.bedroom
      title: Bedroom
      entities:
        - switch.sovrum_1
        - switch.sovrum_2
### Kitchen Camera
    - type: picture-glance
      camera_image: camera.kitchen
      title: Kitchen
      entities:
        - light.kitchen_lights
### Office Camera
    - type: picture-glance
      camera_image: camera.office
      title: Office
      entities:
        - light.livingroom_ambient_lights
### Foodstation Camera
    - type: picture-glance
      camera_image: camera.foodstation
      title: Foodstation
      entities:
        - light.livingroom_ambient_lights
