- platform: broadlink
  host: 192.168.1.5
  mac: '34:ea:34:40:78:ff'
  switches:
    # Will work on most Phillips TVs:
    tv_phillips:
      friendly_name: "Andersson Tv Power"
      command_on: 'JgAwAB8cHxw8HR4cHxwfOjwcHzkfHDwcHwALvB8cHxw8HB8cHxwfOT0cHjofHDwcHwANBQAAAAAAAAAA'
      command_off: 'JgBIAB8cPRwfGx8cHxwfOT0cHzkfHDwcHwALvB8cPBwfHB8cHxwfOT0bIDkfHDwcHwALvB8cPBwfHB8cHxwfOTwcHzkfHD0cHwANBQ=='
    # Will work on most LG TVs
    amp_sony:
      friendly_name: "Sony STR DN1040"
      command_on: 'JgCIAFATKBMVEikSFRIpExUSFRIVExUSFRIVEygTKBMVEhUAAsRQEikSFRIpExUSKRIVEhUTFRIVEhUTFRIpEikSFRMVAALDUBIpExUSKRIVEikSFRMVEhUSFhIVEhUSKRMoExUSFQACxVASKRIVEikSFhIpEhUSFRMVEhUSFRMVEikSKRIVEhYADQU='
      command_off: 'JgCqAFATKBMVEikSFRIpExUSFRIVExUSFRIVEygTKBMVEhUAAsNREikSFRIpEhUTKRIVEhUTFRIVEhUTFRIpEikSFRIWAALDUBMoExUSKRIVEikSFRMVEhUSFhIVEhUTKBMoExUSFQACxVASKRIVEikTFRIpEhUSFRMVEhUSFRMVEikSKRIVExUAAsRQEikSFRMoExUSKRIVExUSFRIVExUSFRIpEikSFRMVAA0FAAAAAAAAAAAAAAAAAAA='
    sony_chromecast:
      friendly_name: "Sony Chromecast"
      command_on: 'JgBmAFASKRIWEikSKRIpEikSKRIVEhUTFRIVEikSKRIWEhUAAohQEykSFRIpEikSKRIpEikSFRMVEhUSFhIpEikSFRIVAAKJUBIpEhYSKRIpEikSKRIpEhUSFRMVEhUSKRIpEhYSFQANBQAA'
    sony_plex:
      friendly_name: "Sony Plex"
      command_on: 'JgCqAFATFRIpEhUSFhIVEikSFhIVEhUSFhIVEikSKRIVExUAAtdQEhYSKRIVEhYSFRIpEhUSFhIVEhUTFRIpEikSFRIWAALXUBIWEikSFRIVEhYSKRIVEhYSFRIVEhYSKRIpEhUSFgAC2FASFhIpEhUSFRMVEikSFRIWEhUSFRIWEikSKRIVEhYAAthQEhUTKBMVEhUSFhIpEhUSFRMVEhUSFhIpEikSFRIVAA0FAAAAAAAAAAAAAAAAAAA='
    sony_tv:
      friendly_name: "Sony TV"
      command_on: 'JgCqAFASKRIpExUSFRIWEhUSFRIWEhUSFRIWEikSKRIVEikAAsRQEikSKRIVExUSFRIWEhUSFRIWEhUSFRIpEikTFRIpAALDUBIpEygTFRIVEhYSFRIVEhYSFRIVEhYSKRIpEhUSKQACxVASKRIpEhUTFRIVEhUTFRIVEhYSFRIVEikSKRMVEikAAsRQEikSKRMVEhUSFRMVEhUSFhIVEhUSFhIpEikSFRIpAA0FAAAAAAAAAAAAAAAAAAA='
    sony_radio:
      friendly_name: "Sony Radio"
      command_on: 'JgCIAFESFRMVEhUSKRIpEhYSFRIVEhYSFRIVEygTKBMVEhUAAtdQExUSFRIVEykSKRIVEhUTFRIVEhUTFRIpEikSFRIWAALXUBIVExUSFRIpEikSFhIVEhUTFRIVExQTKBMpEhUSFQAC2FESFRIVExUSKRIpEhUSFhIVEhUTFRIVEikSKRIWEhUADQU='
    sony_steam:
      friendly_name: "Sony Steam link"
      command_on: 'JgBmAFATFRIVEikSKRIpEikSKRMVEhUSFRMVEikSKRIVEhYAApxQEhUTFRIpEikSKRIpEikSFRMVEhUSFRMpEikSFRIVAAKdUBIVEhYSKRIpEikSKRIpEhUSFhIVEhUTKBMpEhUSFQANBQAA'
# Qlima heater:
    qlima:
      friendly_name: "Qlima Luftpump"
      command_off: 'JgDKAJGQEzQUEBQ0FDQUEBMREzUTERMREzUTERMREzQUNBQQFDQUEBM1EzQUNBQ0ExETNRM0FDQUERMRExAUERM0FBAUEBQ0FDQTNRMRExETERMRExETERMRExETNBQ0FDQTNBQ0Eq2SjhQ0FBAUNBQ0ExETERM0FBETERM0FBAUEBQ0FDQTERM1ExETNBQ0FDQUNBMREzQUNBQ0FBAUEBQQFBAUNBMRExETNRM0FDQUEBQQFBAUEBQQFBAUEBQQFDQUNBM0FDQUNBEADQUAAAAAAAAAAAAAAAAAAA=='
      command_on: 'JgDKAJSNFTMUEBQ0FDUTEBQQFDQUEBQQFDQUEBQQFDMVMxQQFDQUEBQQFDQUNBQ0FDMVMxQ0FDQUNBQQFBAUEBQQFBAUEBQ0FBAUEBQzFTMVMxQQFBAUEBQ0FDQUEBQQFBAUNBQzFKuTjhQ0FBAUMxUzFQ8VDxUyFRAUEBUzFBAUEBQ0FDQUEBQ0FBAUEBQ0FDMVMxQ0FDQUMxUzFTMUEBQQFBAUEBUPFQ8VMxUPFQ8VMxQ0FDMVEBQQFBAUMxUzFBAUEBQQFDQUNBQADQUAAAAAAAAAAAAAAAAAAA=='
