######################################################################
##  Switches in the Greenhouse
######################################################################
- platform: mqtt
  name: "Waterbed 1"
  state_topic: "/greenhouse/water_1/switch"
  command_topic: "/greenhouse/gpio/0"
  payload_on: "0"
  payload_off: "1"
  optimistic: true
  qos: 0
- platform: mqtt
  name: "Waterbed 2"
  state_topic: "/greenhouse/water_2/switch"
  command_topic: "/greenhouse/gpio/14"
  payload_on: "0"
  payload_off: "1"
  optimistic: true
  qos: 0
- platform: mqtt
  name: "Waterbed 3"
  state_topic: "/greenhouse/water_3/switch"
  command_topic: "/greenhouse/gpio/12"
  payload_on: "0"
  payload_off: "1"
  optimistic: true
  qos: 0
- platform: mqtt
  name: "Waterbed 4"
  state_topic: "/greenhouse/water_4/switch"
  command_topic: "/greenhouse/gpio/13"
  payload_on: "0"
  payload_off: "1"
  optimistic: true
  qos: 0
