- platform: template
  sensors:
    side_door:
      friendly_name: "Dörr: Groventré"
      value_template: >-
        {% if is_state('switch.dorr_groventre', 'on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      icon_template: >
        {% if is_state('switch.dorr_groventre', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
    patio_door:
      friendly_name: "Dörr: Altanen"
      value_template: >-
        {% if is_state('switch.dorr_altan', 'on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      icon_template: >
        {% if is_state('switch.dorr_altan', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
    bathroomdoor:
      friendly_name: "Dörr: Badrummet"
      value_template: >-
        {% if is_state('switch.bathroom_door', 'on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      icon_template: >
        {% if is_state('switch.bathroom_door', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
