- platform: template
  sensors:
    side_door_lock:
      friendly_name: "Lock: Groventré"
      value_template: >-
        {% if is_state('switch.dorr_groventre_lock', 'on') %}
          Locked
        {% else %}
          Unlocked
        {% endif %}
      icon_template: >
        {% if is_state('switch.dorr_groventre_lock', 'on') %}
          mdi:lock
        {% else %}
          mdi:lock-open
        {% endif %}
