esphomeyaml:
  name: Test
  platform: ESP8266
  board: d1_mini_pro

wifi:
  ssid: 'Katrinelund'
  password: 'Isaksson81'

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: 'Isaksson81'

ota:
  password: 'Isaksson81'
