- alias: 'Luftdata Lost Connection'
  initial_state: true
  trigger:
  - entity_id: device_tracker.luftdata
    from: 'home'
    platform: state
    to: 'not_home'
  action:
  - data:
      message: Luftdata lost connection
      target:
      - channel/katrinelund
    service: notify.katrinelund

- alias: 'Luftdata Regained Connection'
  initial_state: true
  trigger:
  - entity_id: device_tracker.luftdata
    from: 'not_home'
    platform: state
    to: 'home'
  action:
  - data:
      message: Luftdata regained connection
      target:
      - channel/katrinelund
    service: notify.katrinelund
