- alias: 'Pumphuset'
  id: aunxt7hFJ3PHrELZV8m6sB
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.pumphus_temperature
    below: 2
  action:
    service: notify.ringvattnet
    data:
      message: "Temperaturen i pumphuset är {{ states.sensor.pumphus_temperature.state }}ºC och utetemperaturen är {{ states.sensor.ute_temperature.state }}ºC"
      title: "Varning: Pumphuset"

- alias: 'Pumphuset Varm'
  id: Nn73tWqRsSkfKHDZM2YEBc
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.pumphus_temperature
    above: 30
  action:
    service: notify.ringvattnet
    data:
      message: "Temperaturen i pumphuset är {{ states.sensor.pumphus_temperature.state }}ºC, Skynda dig att öppna!"
      title: "Varning: Pumphuset"

- alias: 'Frys.forrad'
  id: uNV62MSe8XTZhbdksDEKRL
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.frys_forrad_temperature
    above: -10
  action:
    service: notify.ringvattnet
    data:
      message: "Temperaturen i Frys 1 är {{ states.sensor.frys_forrad_temperature.state }}ºC"
      title: "Varning: Frys 1"

#- alias: 'Frys.forrad_2'
#  id: 8E2AvTCrXGBfu7N4DHwgpR
#  initial_state: true
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.frys_2_forrad_temperature
#    above: -10
#  action:
#    service: notify.ringvattnet
#    data:
#      message: "Temperaturen i Frys 2 är {{ states.sensor.frys_2_forrad_temperature.state }}ºC"
#      title: "Varning: Frys 2"