### Turn on carheater on weekdays if temp is below 5
- alias: Period starts
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.period_starts
    to: 'on'
  action:
    - service: remember_the_milk.naesstrom_create_task
      data_template:
        name: "Börja ta primolut 16 days #Personligt +sussaisaksson@gmail.com"
        id: "69"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.period_starts
