- alias: 'add event to google cal'
  initial_state: true
  trigger:
  - at: '22:00:00'
    platform: time
  action:
    - service: google.add_event
      data:
        calendar_id: !secret familycal
        summary: "Testevent Automation"
        in:
          days: 5