- alias: 'Erik is Home TTS'
  trigger:
  - entity_id: device_tracker.erik
    from: 'Away'
    platform: state
    to: 'Just Arrived'
  action:
    service: tts.google_say
    entity_id: media_player.office
    data:
      message: Erik kom just hem!
      language: 'sv'

- alias: 'Sussa is Home TTS'
  trigger:
  - entity_id: device_tracker.sussa
    from: 'Away'
    platform: state
    to: 'Just Arrived'
  action:
    service: tts.google_say
    entity_id: media_player.office
    data:
      message: The queen just arrived!
#      language: 'sv'

- alias: Octoprint:Fail (TTS)
  initial_state: true
  trigger:
  - entity_id: binary_sensor.octoprint_printing_error
    from: 'off'
    platform: state
    to: 'on'
  action:
    service: tts.google_say
    entity_id: media_player.office
    data:
      message: Något gick fel med din 3d utskrift.
      language: 'sv'