- alias: 'Lamp: Turn on at sun set'
  initial_state: true
  trigger:
    platform: sun
    event: sunset
    offset: '-00:45:00'
  action:
  - service: switch.turn_on
    entity_id:
      - switch.vagglampa
      - switch.skapsbelysning
  - service: scene.turn_on
    entity_id: scene.livingroom_normal
