- alias: 'Lamp: Turn off after sunrise'
  initial_state: true
  trigger:
  - event: sunrise
    offset: +00:45:00
    platform: sun
  action:
    - service: light.turn_off
      entity_id:
      - light.livingroom_ambient_lights
      - light.blomlampa
