- alias: 'Lamp: Turn on at sun set'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:45:00'
  action:
  - service: light.turn_on
    entity_id:
      - group.bedroom
  - service: scene.turn_on
    entity_id: scene.livingroom_normal
