notify:
  - name: safeland
    platform: rest
    method: POST
    verify_ssl: false
    headers: 
      content-type: 'application/json; charset=utf-8'
    resource: !secret safeland_hook

binary_sensor:
  - platform: template
    sensors:
      side_door:
        unique_id: h5635aQ8XcZL
        device_class: opening
        value_template: "{{ is_state('sensor.side_door', 'Open') }}"
        icon_template: >-
          {% if is_state("binary_sensor.side_door", "on") %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}
      front_door:
        unique_id: cTuqLy7VmnZ7
        device_class: opening
        value_template: "{{ is_state('sensor.front_door', 'Open') }}"
        icon_template: >-
          {% if is_state("binary_sensor.front_door", "on") %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}
      patio_door:
        unique_id: 2NvEAsZ5A4zJ
        device_class: opening
        value_template: "{{ is_state('sensor.patio_door', 'Open') }}"
        icon_template: >-
          {% if is_state("binary_sensor.patio_door", "on") %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}

      people_home:
        unique_id: u79cpukLqkey
        value_template: >-
          {{ is_state('person.erik', 'home')
             or is_state('person.sussa', 'home')
             or is_state('binary_sensor.attic_motion', 'on')
             or is_state('binary_sensor.bathroom_motion_2', 'on')
             or is_state('binary_sensor.bedroom_motion', 'on')
             or is_state('binary_sensor.kitchen_motion', 'on')
             or is_state('binary_sensor.livingroom_motion', 'on')
             or is_state('binary_sensor.office_motion', 'on')
             or is_state('binary_sensor.vpir_hall', 'on')
          }}