binary_sensor:
  - platform: mqtt
    name: "sonoff-sussas_heater lwt"
    state_topic: "tele/carheater_1/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

  - platform: mqtt
    name: "sonoff-eriks_heater lwt"
    state_topic: "tele/carheater_2/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

switch:
  - platform: mqtt
    name: "Carheater Erik (sonoff)"
    command_topic: "cmnd/carheater_2/POWER"
    state_topic: "stat/carheater_2/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Carheater Sussa (sonoff)"
    command_topic: "cmnd/carheater_1/POWER"
    state_topic: "stat/carheater_1/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

sensor:
## Eriks Sensorer
- platform: mqtt
  name: "Eriks Carheater 2 Todays Energy"
  state_topic: "tele/carheater_2/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Today"] }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "Eriks Carheater 2 Power"
  state_topic: "tele/carheater_2/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: "W"
- platform: mqtt
  name: "Eriks Carheater 2 Voltage"
  state_topic: "tele/carheater_2/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
  unit_of_measurement: "V"
- platform: mqtt
  name: "Eriks Carheater 2 Current"
  state_topic: "tele/carheater_2/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Current"] }}'
  unit_of_measurement: "A"
- platform: template
  sensors:
    eriks_carheater_cost:
      friendly_name: "Eriks Carheater daily cost"
      unit_of_measurement: ' kr'
      value_template: "{{ states.sensor.eriks_carheater_2_todays_energy.state | multiply(2.2478) | round(2)}}"

## Sussas sensorer
- platform: mqtt
  name: "Sussas Carheater 1 Todays Energy"
  state_topic: "tele/carheater_1/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Today"] }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "Sussas Carheater 1 Power"
  state_topic: "tele/carheater_1/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: "W"
- platform: mqtt
  name: "Sussas Carheater 1 Voltage"
  state_topic: "tele/carheater_1/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
  unit_of_measurement: "V"
- platform: mqtt
  name: "Sussas Carheater 1 Current"
  state_topic: "tele/carheater_1/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Current"] }}'
  unit_of_measurement: "A"
- platform: template
  sensors:
    sussas_carheater_cost:
      friendly_name: "Sussas Carheater daily cost"
      unit_of_measurement: ' kr'
      value_template: "{{ states.sensor.sussas_carheater_1_todays_energy.state | multiply(2.2478) | round(2)}}"

## Input switches
input_boolean:
  workdays_only_sussa:
    name: Only active on workdays sussa
    initial: true
  workdays_only_erik:
    name: Only active on workdays erik
    initial: true

automation:
  - alias: "Engine heater activate erik"
    initial_state: true
    trigger:
      platform: time
      at: '04:00:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.arbetsdag
          state: 'on'
        - condition: template
          value_template: "{{states.weather.smhi_home.attributes.temperature < 10}}"
#        - condition: numeric_state
#          entity_id: 'sensor.outside_temperature'
#          below: 5
    # If the above conditions are fulfilled, ie. you are home and it's a workday
    # then activate the heater on your selected time
    action:
      - service: switch.turn_on
        # Don't forget to select the correct switch
        entity_id: switch.carheater_erik_sonoff

  - alias: "Engine heater activate sussa"
    initial_state: true
    trigger:
      platform: time
      at: '04:00:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.arbetsdag
          state: 'on'
        - condition: template
          value_template: "{{states.weather.smhi_home.attributes.temperature < 10}}"
    # If the above conditions are fulfilled, ie. you are home and it's a workday
    # then activate the heater on your selected time
    action:
      - service: switch.turn_on
        # Don't forget to select the correct switch
        entity_id: switch.carheater_sussa_sonoff


  # Automation 2 turns off the car heater at the set delay.
  - alias: "Engine heater deactivate both"
    initial_state: true
    trigger:
      platform: time
      at: '07:30:00'
    action:
      - service: switch.turn_off
        # Don't forget to select the correct switch
        entity_id:
          - switch.carheater_erik_sonoff
          - switch.carheater_sussa_sonoff
