######
##
##    Detta är en "package" fil som visar antal smittade i Sverige per län/region
##    Datat kommer via SVTs api
##    Automationen är ett exempel för att pusha ut en talad röst till en Google Home-enhet med antalet smittade i Sverige och i Värmland
## 
##    Installation
##    - Lägg till under "homeassistant:" i din configuration.yaml fil "packages: !include_dir_named packages" (utan "")
##    - I /config/ skapa en mapp som heter "packages"
##    - Lägg in nedan kod i en fil som förslagsvis heter covid19.yaml i den mappen
##    - Kontrollera din konfiguration och starta om Home Assistant
##
######

automation:
  - id: 'corona_sweden_alert'
    alias: Nya Coronafall i Sverige - Meddela
    initial_state: 'on'
    trigger:
    - entity_id: sensor.covid_19_svt_antal_smittade_totalt
      platform: state
    condition:
    - condition: time
      after: '08:00:00'
      before: '21:00:00'
#    - condition: state
#      entity_id: alarm_control_panel.my_alarm
#      state: disarmed
    action:
    - data:
        entity_id: media_player.googlehome0719
        volume_level: '0.5'
      service: media_player.volume_set
    - data_template:
        entity_id: media_player.googlehome0719
        message: 'Nya fall av Coronavirus i Sverige har upptäckts, just nu är antalet {{ states.sensor.covid_19_svt_antal_smittade_totalt.state }} stycken smittade varav {{ states.sensor.covid_19_svt_antal_smittade_kronoberg.state }} i Kronoberg!'
        language: 'sv'
      service: tts.google_translate_say
    - delay: 00:00:15
    - data:
        entity_id: media_player.googlehome0719
      service: media_player.turn_off

sensor:
  - platform: rest
    resource: https://www.svt.se/special/articledata/2322/sverige.json
    name: COVID-19-svt
    scan_interval: 900
    json_attributes:
      - total
      - data
    value_template: '{{ value_json.data_updated }}'

  - platform: template
    sensors:
      covid_19_svt_antal_smittade_stockholm: 
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Stockholm' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_stockholm: 
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Stockholm' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_varmland:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Värmland' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_varmland:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Värmland' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_vastragotaland:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Västra Götaland' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_vastragotaland:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Västra Götaland' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_skane:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Skåne' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_skane:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Skåne' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_halland:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Halland' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_halland:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Halland' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_jonkoping:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Jönköping' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_jonkoping:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Jönköping' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_uppsala:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Uppsala' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_uppsala:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Uppsala' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_ostergotland:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Östergötland' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_ostergotland:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Östergötland' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_sodermanland:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Södermanland' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_sodermanland:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Södermanland' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_kronoberg:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Kronoberg' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_kronoberg:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Kronoberg' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_vasternorrland:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Västernorrland' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_vasternorrland:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Västernorrland' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_orebro:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Örebro' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_orebro:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Örebro' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_jamtland_harjedalen:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Jämtland/Härjedalen' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_jamtland_harjedalen:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Jämtland/Härjedalen' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_blekinge:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Blekinge' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_blekinge:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Blekinge' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_norrbotten:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Norrbotten' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_norrbotten:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Norrbotten' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_vastmanland:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Västmanland' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_vastmanland:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Västmanland' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_kalmar:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Kalmar län' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_kalmar:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Kalmar län' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_gavleborg:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Gävleborg' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_gavleborg:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Gävleborg' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_dalarna:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Dalarna' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_dalarna:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Dalarna' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_gotland:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Gotland' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_gotland:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Gotland' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_ovriga:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Ej specificerat' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.antal }}
      covid_19_svt_antal_avlidna_ovriga:
        unit_of_measurement: 'Personer'
        value_template: >
          {% set name = 'Ej specificerat' %}
          {% set value = state_attr('sensor.covid_19_svt', 'data') | selectattr('namn','eq',name) | list | first %}
          {{ value.dead }}
      covid_19_svt_antal_smittade_totalt:
        value_template: '{{ states.sensor.covid_19_svt.attributes["total"] }}'
        unit_of_measurement: 'Personer'