#-------------------------------------------
#  RSS Podcast Alerting function Packages
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
feedreader:
    urls:
      - https://hasspodcast.io/feed/podcast #HA Podcast Feed
      - https://us12.campaign-archive.com/feed?u=45cab4343ffdbeb9667c28a26&id=e01847e94f #This is CCOSTAN's Smart Home Blog feed
# - http://feeds.feedburner.com/RecentCommitsToBearStoneHA - This is the Repo Commit feed.
#-------------------------------------------

automation:
  - alias: Send notification of RSS feed title when updated
    initial_state: true
    trigger:
      platform: event
      event_type: feedreader

    action:
      - service: notify.discord
        data_template:
          title: "New RSS Item available"
          message: "New RSS Item - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }} {{trigger.event.data.title}}"
          data:
            url: "{{trigger.event.data.link}}"
          target: 476413377623752704
      - service: persistent_notification.create
        data_template:
          title: "{{trigger.event.data.title}}"
          message: "New RSS item available - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
          notification_id: "update_available"
