# example Json
# {"temp":27,"target":27,"locked":false ,"air":false,"celsius":true,"heating" :false,"heater":true,"filter":true,"p ower":true,"time":"2020-09-25 16:15:58","clts":346537,"heattime":21 7034,"uptime":1049253,"airtime":62,"f iltertime":680695,"cost":184.0584,"au to":true,"dsp":" 27"}"

sensor:
  - platform: mqtt
    name: "Pool Temp"
    state_topic: "BW-1.27_MQTT/message"
    unit_of_measurement: 'ºC'
    value_template: "{{ value_json.temp }}"

binary_sensor:
  - platform: mqtt
    name: "Heating"
    state_topic: "BW-1.27_MQTT/message"
    device_class: heat
    payload_on: "true"
    payload_off: "false"