sensor:
  - platform: plex_recently_added
    name: Recently Added Movies # will create sensor.recently_added_movies
    token: !secret plex_token
    host: !secret plex_host
    port: 32400
    section_types:
      - movie

  - platform: plex_recently_added
    name: Recently Added TV # will create sensor.recently_added_tv
    token: !secret plex_token
    host: !secret plex_host
    port: 32400
    section_types:
      - show

command_line:
  - binary_sensor:
      command: curl -I http://192.168.1.10:32400/library/sections?X-Plex-Token=b9xuhP5mnkj4AEGyibRu > /dev/null 2>&1 && echo on || echo off
      name: "Plex Media Server"
      device_class: connectivity
      payload_on: "on"
      payload_off: "off"
      scan_interval: 30
