################################################################
## Packages / Secrets Container
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "secrets_container"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Sensor
    ################################################

    sensor.secrets:
      <<: *customize
      friendly_name: "Secrets"
      hidden: true
      icon: mdi:file-lock
      temp_hash_1: !secret temp_nu_hash

################################################
## Sensor
################################################

template:
  - sensor:
      - name: "Secrets"
        unique_id: secrets_container
        state: "Secrets Container"
