##############################################
# Fetches the latest warnings from SMHI and filters out the area that you select
# Replace the 3 digit code after areaDesc to your region
# List can be found at bottom of this file or at the URl below
# https://docs.google.com/spreadsheets/d/1wHKv-cUuqDnqQARbUTb5SR9MPHa93lbU9LzD39tUShI/edit?usp=sharing
##############################################

sensor:
  - platform: rest
    resource: https://opendata-download-warnings.smhi.se/api/version/2/alerts.json
    name: "SMHI Warning - severity"
    value_template: >-
      {% set areaDesc = '018' %}
      {% set alert = value_json['alert'] | selectattr('info.area.areaDesc','eq',areaDesc) | list | first %}
      {{ alert.info.severity }}

  - platform: rest
    resource: https://opendata-download-warnings.smhi.se/api/version/2/alerts.json
    name: "SMHI Warning - urgency"
    value_template: >-
      {% set areaDesc = '018' %}
      {% set alert = value_json['alert'] | selectattr('info.area.areaDesc','eq',areaDesc) | list | first %}
      {{ alert.info.urgency }}

  - platform: rest
    resource: https://opendata-download-warnings.smhi.se/api/version/2/alerts.json
    name: "SMHI Warning - certainty"
    value_template: >-
      {% set areaDesc = '018' %}
      {% set alert = value_json['alert'] | selectattr('info.area.areaDesc','eq',areaDesc) | list | first %}
      {{ alert.info.certainty }}

  - platform: rest
    resource: https://opendata-download-warnings.smhi.se/api/version/2/alerts.json
    name: "SMHI Warning - type"
    value_template: >-
      {% set areaDesc = '018' %}
      {% set alert = value_json['alert'] | selectattr('info.area.areaDesc','eq',areaDesc) | list | first %}
      {{ alert.info.event }}

  - platform: rest
    resource: https://opendata-download-warnings.smhi.se/api/version/2/alerts.json
    name: "SMHI Warning - location"
    value_template: >-
      {% set areaDesc = '018' %}
      {% set alert = value_json['alert'] | selectattr('info.area.areaDesc','eq',areaDesc) | list | first %}
      {{ alert.info.headline }}

  - platform: rest
    resource: https://opendata-download-warnings.smhi.se/api/version/2/alerts.json
    name: "SMHI Warning - event"
    value_template: >-
      {% set areaDesc = '018' %}
      {% set alert = value_json['alert'] | selectattr('info.area.areaDesc','eq',areaDesc) | list | first %}
      {{ alert.info.eventCode[1].value }}

  - platform: rest
    resource: https://opendata-download-warnings.smhi.se/api/version/2/alerts.json
    name: "SMHI Warning - attributes"
    value_template: >-
      {% set areaDesc = '018' %}
      {% set alert = value_json['alert'] | selectattr('info.area.areaDesc','eq',areaDesc) | list | first %}
      {{ alert.info }}
    json_attributes:
      - urgency
      - severity
      - certainty
      - eventCode[1].value

# District    District View Category	District View Name
# 001	        land	                Norrbottens län,norra Lapplandsfjällen
# 002	        land                    Västerbottens län,södra Lapplandsfjällen
# 003	        land	                Jämtlands län,Jämtlandsfjällen
# 004	        land	                Jämtlands län,Härjedalsfjällen
# 005	        land		            Dalarnas län,Dalafjällen
# 006	        land		            Blekinge län
# 007	        land		            Västra Götalands län,Bohuslän och Göteborg
# 008	        land		            Dalarnas län utom Dalafjällen
# 009	        land		            Västra Götalands län,inre Dalsland
# 010	        land		            Gotlands län
# 011	        land		            Gävleborgs län inland
# 012	        land		            Hallands län
# 013	        land		            Jämtlands län utom fjällen
# 014	        land		            Jönköpings län,västra delen utom syd om Vättern
# 015	        land		            Jönköpings län,östra delen
# 016	        land		            Kalmar län utom Öland
# 017	        land		            Kronobergs län,västra delen
# 018	        land		            Kronobergs län,östra delen
# 019	        land		            Norrbottens län inland
# 020	        land		            Norrbottens län kustland
# 021	        land		            Stockholms län,Roslagskusten
# 022	        land		            Västra Götalands län,Sjuhäradsbygden och Göta älv
# 023	        land		            Skåne län utom Österlen
# 024	        land		            Gävleborgs län kustland
# 025	        land		            Stockholms län utom Roslagskusten
# 026	        land		            Jönköpings län,syd om Vättern
# 027	        land		            Västra Götalands län,sydväst Vänern
# 028	        land		            Södermanlands län
# 029	        land		            Uppsala län utom Upplandskusten
# 030	        land		            Uppsala län,Upplandskusten
# 031	        land		            Värmlands län
# 032	        land		            Västerbottens län inland
# 033	        land		            Västerbottens län kustland
# 034	        land		            Västernorrlands län
# 035	        land		            Västmanlands län
# 036	        land		            Västra Götalands län,norra Västergötland
# 037	        land		            Kalmar län,Öland
# 038	        land		            Örebro län
# 039	        land		            Östergötlands län
# 040	        land		            Skåne län,Österlen
# 041	        sea		                Bottenviken
# 042	        sea		                Norra Kvarken
# 043	        sea		                Norra Bottenhavet
# 044	        sea		                Södra Bottenhavet
# 045	        sea		                Ålands hav
# 046	        sea		                Skärgårdshavet
# 047	        sea		                Finska viken
# 048	        sea		                Norra Östersjön
# 049	        sea		                Mellersta Östersjön
# 050	        sea		                Rigabukten
# 051	        sea		                Sydöstra Östersjön
# 052	        sea		                Södra Östersjön
# 053	        sea		                Sydvästra Östersjön
# 054	        sea		                Bälten
# 055	        sea		                Öresund
# 056	        sea		                Kattegatt
# 057	        sea		                Skagerack
# 058	        sea		                Vänern