homeassistant:

  customize:
    sensor.house_energy_usage:
      last_reset: "2021-07-30T00:00:00+00:00"
    sensor.house_power_usage:
      last_reset: "2021-07-30T00:00:00+00:00"

sensor:
  - platform: mqtt
    state_topic: "EspSparsnasGateway/+/state"
    name: "House power usage"
    unit_of_measurement: "W"
    value_template: '{{ float(value_json.watt) | round(0)  }}'
    icon: mdi:flash-circle
    state_class: measurement
    device_class: power

  - platform: mqtt
    state_topic: "EspSparsnasGateway/+/state"
    name: "House energy usage"
    unit_of_measurement: "kWh"
    value_template: '{{ float(value_json.total) | round(0)  }}'
    icon: mdi:flash-circle
    state_class: measurement
    device_class: energy

  - platform: mqtt
    state_topic: "EspSparsnasGateway/+/state"
    name: "House energy meter batt"
    unit_of_measurement: "%"
    value_template: '{{ float(value_json.battery) }}'
    icon: mdi:battery-outline

  - platform: mqtt
    state_topic: "EspSparsnasGateway/+/state"
    name: "House energy meter power"
#    unit_of_measurement: "%"
    value_template: '{{ float(value_json.power) }}'
    icon: mdi:power-socket-eu
    state_class: measurement

  - platform: mqtt
    state_topic: "EspSparsnasGateway/+/state"
    name: "House energy meter signal"
    unit_of_measurement: "dBm"
    value_template: '{{ float(value_json.rssi) }}'
    icon: mdi:antenna