sensor:
  - platform: template
    sensors:
      sunrise_today:
        unique_id: 9K5KSePnPmtsk5B368L7
        friendly_name: "Sunrise today"
        value_template: "{{ state_attr('sensor.sunrise', 'today') }}"
      sunrise_tomorrow:
        unique_id: hp7U7EKM7YMRRWfzszRv
        friendly_name: "Sunrise tomorrow"
        value_template: "{{ state_attr('sensor.sunrise', 'tomorrow') }}"
      sunset_today:
        unique_id: mmrg4UZZhcYEKHqq28aq
        friendly_name: "Sunset today"
        value_template: "{{ state_attr('sensor.sunset', 'today') }}"
      sunset_tomorrow:
        unique_id: F296VMe2HuM94PMpBxeT
        friendly_name: "Sunset tomorrow"
        value_template: "{{ state_attr('sensor.sunset', 'tomorrow') }}"
      daylight_today:
        unique_id: sRn8W5QSLaHKkq5mmZxx
        friendly_name: "Daylight today"
        value_template: "{{ state_attr('sensor.sunset', 'today') - state_attr('sensor.sunrise', 'today') }}"
      daylight_tomorrow:
        unique_id: Xkmsvv9sjj8RQebp686V
        friendly_name: "Daylight tomorrow"
        value_template: "{{ state_attr('sensor.sunset', 'tomorrow') - state_attr('sensor.sunrise', 'tomorrow') }}"
      daylight_change:
        unique_id: DTVLtRD58scctyeGEE9R
        friendly_name: "Daylight change"
        value_template: "{{( state_attr('sensor.sunset', 'tomorrow') - state_attr('sensor.sunrise', 'tomorrow') ) - (state_attr('sensor.sunset', 'today') - state_attr('sensor.sunrise', 'today') )}}"

  - platform: sun2
    monitored_conditions:
      - solar_midnight
      - astronomical_dawn
      - nautical_dawn
      - dawn
      - sunrise
      - solar_noon
      - sunset
      - dusk
      - nautical_dusk
      - astronomical_dusk
      - daylight
      - civil_daylight
      - nautical_daylight
      - astronomical_daylight
      - night
      - civil_night
      - nautical_night
      - astronomical_night
      - elevation
      - min_elevation
      - max_elevation
binary_sensor:
  - platform: sun2
    monitored_conditions:
      - elevation
      - elevation: 3
      - elevation:
          above: -6
          name: Above Civil Dawn