sensor:
  - platform: untappd
    username: Naesstrom
    id: !secret untappd_ID
    secret: !secret untappd_Secret

### Templating for the untappd lovelace card (https://sharethelove.io/picture-elements-cards/untappd-card)
  - platform: template
    sensors:
      untappd_badge:
       value_template: "Recent Badge: {{ states.sensor.untappd_last_badge_naesstrom.attributes.badge }} (Level {{ states.sensor.untappd_last_badge_naesstrom.attributes.level }})"

  - platform: template
    sensors:
      untappd_beer:
       value_template: "Recent Beer: {{ states.sensor.untappd_last_check_in_naesstrom.attributes.beer }} ({{ states.sensor.untappd_last_check_in_naesstrom.attributes.abv }})"

  - platform: template
    sensors:
      untappd_followings:
       unit_of_measurement: followers
       value_template: "{{ states.sensor.untappd_last_check_in_naesstrom.attributes.followings }}"

  - platform: template
    sensors:
      untappd_checked:
       unit_of_measurement: checkins
       value_template: "{{ states.sensor.untappd_last_check_in_naesstrom.attributes.checkins }}"

  - platform: template
    sensors:
      untappd_total_beers:
       unit_of_measurement: beers
       value_template: "{{ states.sensor.untappd_last_check_in_naesstrom.attributes.total_beers }}"

  - platform: template
    sensors:
      untappd_total_badges:
       unit_of_measurement: badges
       value_template: "{{ states.sensor.untappd_last_check_in_naesstrom.attributes.total_badges }}"

automation:
  - alias: Cheers
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.untappd_last_check_in_naesstrom
    condition:
      condition: state
      entity_id: sensor.untappd_last_check_in_naesstrom
      state: Today
    action:
      - delay: '00:01:30'
      - service: notify.discord_hook
        data_template:
          message: "Cheers! {{ states.sensor.untappd_last_check_in_naesstrom.attributes.beer }} was just rated a {{ states.sensor.untappd_last_check_in_naesstrom.attributes.score }} "