automation:
- alias: 'Tvättmaskinen'
  initial_state: true
  trigger:
  - entity_id: binary_sensor.washing_machine_stat
    from: 'on'
    platform: state
    to: 'off'
  action:
    - service: notify.katrinelund
      data:
        message: Tvätten är klar!
        target:
        - channel/katrinelund
    - service: notify.discord_webhook
      data:
        message: Tvätten är klar!
        target: 476413377623752704
    - service: tts.google_translate_say
      entity_id: media_player.google_home_group
      data:
        message: Tvätten är klar!
        language: 'sv'