homeassistant:
  customize_glob:
    sensor.*wifi*:
      templates:
        hs_color: "if (state === 'Amazing') return [112, 100];
        else if (state === 'Unusable') return [360, 100];
        else if (state === 'Very good') return [182, 100];
        else if (state === 'Okay') return [59, 73];
        else if (state === 'Not good') return [35, 100];"

sensor:
# Wifi quality in the attic
  - platform: template
    sensors:
      wifi_quality_attic:
        friendly_name: 'Wifi Quality (Attic)'
        value_template: >-
          {% if states.sensor.wifi_attic.state | float>=-30 %} Amazing
          {% elif states.sensor.wifi_attic.state | float<-81 %}Unusable
          {% elif states.sensor.wifi_attic.state | float>=-66 | float<-31 %}Very good
          {% elif states.sensor.wifi_attic.state | float>=-70 | float<-67 %}Okay
          {% elif states.sensor.wifi_attic.state | float>=-80 | float<-71 %}Not good
          {%- endif %}
        icon_template: >-
          {% if states.sensor.wifi_attic.state | float>=-30 %}
            mdi:wifi-strength-4
          {% elif states.sensor.wifi_attic.state | float<-81 %}
            mdi:wifi-strength-0
          {% elif states.sensor.wifi_attic.state | float>=-66 | float<-31 %}
            mdi:wifi-strength-3
          {% elif states.sensor.wifi_attic.state | float>=-70 | float<-67 %}
            mdi:wifi-strength-2
          {% elif states.sensor.wifi_attic.state | float>=-80 | float<-71 %}
            mdi:wifi-strength-1
          {%- endif %}

# Wifi quality in the Office
  - platform: template
    sensors:
      wifi_quality_office:
        friendly_name: 'Wifi Quality (Office)'
        value_template: >-
          {% if states.sensor.wifi_office.state | float>=-30 %} Amazing
          {% elif states.sensor.wifi_office.state | float<-81 %}Unusable
          {% elif states.sensor.wifi_office.state | float>=-66 | float<-31 %}Very good
          {% elif states.sensor.wifi_office.state | float>=-70 | float<-67 %}Okay
          {% elif states.sensor.wifi_office.state | float>=-80 | float<-71 %}Not good
          {%- endif %}
        icon_template: >-
          {% if states.sensor.wifi_office.state | float>=-30 %}
            mdi:wifi-strength-4
          {% elif states.sensor.wifi_office.state | float<-81 %}
            mdi:wifi-strength-0
          {% elif states.sensor.wifi_office.state | float>=-66 | float<-31 %}
            mdi:wifi-strength-3
          {% elif states.sensor.wifi_office.state | float>=-70 | float<-67 %}
            mdi:wifi-strength-2
          {% elif states.sensor.wifi_office.state | float>=-80 | float<-71 %}
            mdi:wifi-strength-1
          {%- endif %}

# Wifi quality in the Livingroom
  - platform: template
    sensors:
      wifi_quality_livingroom:
        friendly_name: 'Wifi Quality (Livingroom)'
        value_template: >-
          {% if states.sensor.wifi_livingroom.state | float>=-30 %} Amazing
          {% elif states.sensor.wifi_livingroom.state | float<-81 %}Unusable
          {% elif states.sensor.wifi_livingroom.state | float>=-66 | float<-31 %}Very good
          {% elif states.sensor.wifi_livingroom.state | float>=-70 | float<-67 %}Okay
          {% elif states.sensor.wifi_livingroom.state | float>=-80 | float<-71 %}Not good
          {%- endif %}
        icon_template: >-
          {% if states.sensor.wifi_livingroom.state | float>=-30 %}
            mdi:wifi-strength-4
          {% elif states.sensor.wifi_livingroom.state | float<-81 %}
            mdi:wifi-strength-0
          {% elif states.sensor.wifi_livingroom.state | float>=-66 | float<-31 %}
            mdi:wifi-strength-3
          {% elif states.sensor.wifi_livingroom.state | float>=-70 | float<-67 %}
            mdi:wifi-strength-2
          {% elif states.sensor.wifi_livingroom.state | float>=-80 | float<-71 %}
            mdi:wifi-strength-1
          {%- endif %}

# Wifi quality in the bathroom
  - platform: template
    sensors:
      wifi_quality_bathroom:
        friendly_name: 'Wifi Quality (Bathroom)'
        value_template: >-
          {% if states.sensor.wifi_bathroom.state | float>=-30 %} Amazing
          {% elif states.sensor.wifi_bathroom.state | float<-81 %}Unusable
          {% elif states.sensor.wifi_bathroom.state | float>=-66 | float<-31 %}Very good
          {% elif states.sensor.wifi_bathroom.state | float>=-70 | float<-67 %}Okay
          {% elif states.sensor.wifi_bathroom.state | float>=-80 | float<-71 %}Not good
          {%- endif %}
        icon_template: >-
          {% if states.sensor.wifi_bathroom.state | float>=-30 %}
            mdi:wifi-strength-4
          {% elif states.sensor.wifi_bathroom.state | float<-81 %}
            mdi:wifi-strength-0
          {% elif states.sensor.wifi_bathroom.state | float>=-66 | float<-31 %}
            mdi:wifi-strength-3
          {% elif states.sensor.wifi_bathroom.state | float>=-70 | float<-67 %}
            mdi:wifi-strength-2
          {% elif states.sensor.wifi_bathroom.state | float>=-80 | float<-71 %}
            mdi:wifi-strength-1
          {%- endif %}

# Wifi quality in the kitchen
  - platform: template
    sensors:
      wifi_quality_kitchen:
        friendly_name: 'Wifi Quality (Kitchen)'
        value_template: >-
          {% if states.sensor.wifi_kitchen.state | float>=-30 %} Amazing
          {% elif states.sensor.wifi_kitchen.state | float<-81 %}Unusable
          {% elif states.sensor.wifi_kitchen.state | float>=-66 | float<-31 %}Very good
          {% elif states.sensor.wifi_kitchen.state | float>=-70 | float<-67 %}Okay
          {% elif states.sensor.wifi_kitchen.state | float>=-80 | float<-71 %}Not good
          {%- endif %}
        icon_template: >-
          {% if states.sensor.wifi_kitchen.state | float>=-30 %}
            mdi:wifi-strength-4
          {% elif states.sensor.wifi_kitchen.state | float<-81 %}
            mdi:wifi-strength-0
          {% elif states.sensor.wifi_kitchen.state | float>=-66 | float<-31 %}
            mdi:wifi-strength-3
          {% elif states.sensor.wifi_kitchen.state | float>=-70 | float<-67 %}
            mdi:wifi-strength-2
          {% elif states.sensor.wifi_kitchen.state | float>=-80 | float<-71 %}
            mdi:wifi-strength-1
          {%- endif %}

# Wifi quality in the bedroom
  - platform: template
    sensors:
      wifi_quality_bedroom:
        friendly_name: 'Wifi Quality (Bedroom)'
        value_template: >-
          {% if states.sensor.wifi_bedroom.state | float>=-30 %} Amazing
          {% elif states.sensor.wifi_bedroom.state | float<-81 %}Unusable
          {% elif states.sensor.wifi_bedroom.state | float>=-66 | float<-31 %}Very good
          {% elif states.sensor.wifi_bedroom.state | float>=-70 | float<-67 %}Okay
          {% elif states.sensor.wifi_bedroom.state | float>=-80 | float<-71 %}Not good
          {%- endif %}
        icon_template: >-
          {% if states.sensor.wifi_bedroom.state | float>=-30 %}
            mdi:wifi-strength-4
          {% elif states.sensor.wifi_bedroom.state | float<-81 %}
            mdi:wifi-strength-0
          {% elif states.sensor.wifi_bedroom.state | float>=-66 | float<-31 %}
            mdi:wifi-strength-3
          {% elif states.sensor.wifi_bedroom.state | float>=-70 | float<-67 %}
            mdi:wifi-strength-2
          {% elif states.sensor.wifi_bedroom.state | float>=-80 | float<-71 %}
            mdi:wifi-strength-1
          {%- endif %}