- platform: mjpeg
  mjpeg_url: http://192.168.1.30:4242/video/mjpg.cgi
  still_image_url: http://192.168.1.30:4242/image/jpeg.cgi
  username: !secret camuser
  password: !secret campass1
  name: Kitchen