- platform: generic
  name: DaFang3_still
  username: !secret dafanguser
  password: !secret campass2
  authentication: basic
  still_image_url: https://192.168.1.35/cgi-bin/currentpic.cgi
  verify_ssl: false
  scan_interval: 5